// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniCareERP.Infrastructure.Data;

#nullable disable

namespace UniCareERP.Infrastructure.Migrations
{
    [DbContext(typeof(UniCareDbContext))]
    [Migration("20250708000000_AddInvoiceAndInvoiceItemEntities")] // Updated migration ID
    partial class AddInvoiceAndInvoiceItemEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // --- All previous entities from the last snapshot ---
            // [Copying all entity builders from the previous snapshot here for brevity]
            // ... Identity, ApplicationUser, ApplicationRole, Patient, Appointment, other placeholders ...

            // --- Identity Models ---
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("UniCareERP.Domain.Entities.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("UniCareERP.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("UniCareERP.Domain.Entities.Patients.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");
                    b.Property<string>("Allergies")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("BloodGroup")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");
                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");
                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");
                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");
                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");
                    b.Property<string>("EmergencyContactRelationship")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");
                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");
                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");
                    b.Property<string>("GeneralNotes")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("InsurancePolicyNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");
                    b.Property<string>("InsuranceProvider")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");
                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");
                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");
                    b.Property<string>("MaritalStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");
                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");
                    b.Property<string>("Nationality")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");
                    b.Property<string>("PatientCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");
                    b.Property<string>("PreferredLanguage")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");
                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.ToTable("Patients");
                });

            modelBuilder.Entity("UniCareERP.Domain.Entities.Patients.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("AppointmentDateTime")
                        .HasColumnType("datetime2");
                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");
                    b.Property<string>("DoctorId")
                        .HasColumnType("nvarchar(450)");
                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");
                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");
                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");
                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");
                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("ServiceType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");
                    b.Property<int>("Status")
                        .HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("DoctorId");
                    b.HasIndex("PatientId");
                    b.ToTable("Appointments");
                });

            // --- Updated Invoice and New InvoiceItem Models ---
            modelBuilder.Entity("UniCareERP.Domain.Entities.Finance.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");
                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");
                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");
                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");
                    b.Property<Guid?>("SourceAppointmentId") // Added
                        .HasColumnType("uniqueidentifier");
                    b.Property<int>("Status") // Updated
                        .HasColumnType("int");
                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");
                    b.HasKey("Id");
                    b.HasIndex("PatientId");
                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("UniCareERP.Domain.Entities.Finance.InvoiceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier");
                    b.Property<int>("Quantity")
                        .HasColumnType("int");
                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uniqueidentifier");
                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");
                    b.HasKey("Id");
                    b.HasIndex("InvoiceId");
                    b.ToTable("InvoiceItem");
                });

            modelBuilder.Entity("UniCareERP.Domain.Entities.Finance.GeneralLedgerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");
                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");
                    b.HasKey("Id");
                    b.ToTable("GeneralLedgerAccounts");
                });

            modelBuilder.Entity("UniCareERP.Domain.Entities.HR.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");
                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");
                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");
                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");
                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasFilter("[ApplicationUserId] IS NOT NULL");
                    b.ToTable("Employees");
                });

            modelBuilder.Entity("UniCareERP.Domain.Entities.HR.LeaveRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");
                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uniqueidentifier");
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");
                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("datetime2");
                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");
                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.HasIndex("EmployeeId");
                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("UniCareERP.Domain.Entities.Inventory.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
                    b.Property<string>("BatchNumber")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,2)");
                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");
                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");
                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");
                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");
                    b.Property<int>("ReorderLevel")
                        .HasColumnType("int");
                    b.Property<string>("SupplierInfo")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");
                    b.HasKey("Id");
                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("UniCareERP.Domain.Entities.Inventory.StockTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uniqueidentifier");
                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");
                    b.Property<int>("QuantityChanged")
                        .HasColumnType("int");
                    b.Property<string>("ReferenceId")
                        .HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");
                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("InventoryItemId");
                    b.ToTable("StockTransactions");
                });

            // --- Relationships ---
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("UniCareERP.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("UniCareERP.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("UniCareERP.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("UniCareERP.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniCareERP.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("UniCareERP.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UniCareERP.Domain.Entities.Patients.Appointment", b =>
                {
                    b.HasOne("UniCareERP.Domain.Entities.ApplicationUser", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UniCareERP.Domain.Entities.Patients.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                    b.Navigation("Patient");
                });

            modelBuilder.Entity("UniCareERP.Domain.Entities.Finance.Invoice", b =>
                {
                    b.HasOne("UniCareERP.Domain.Entities.Patients.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.Navigation("Patient");
                });

            modelBuilder.Entity("UniCareERP.Domain.Entities.Finance.InvoiceItem", b =>
                {
                    b.HasOne("UniCareERP.Domain.Entities.Finance.Invoice", "Invoice")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("UniCareERP.Domain.Entities.HR.Employee", b =>
                {
                    b.HasOne("UniCareERP.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithOne()
                        .HasForeignKey("UniCareERP.Domain.Entities.HR.Employee", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.SetNull);
                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("UniCareERP.Domain.Entities.HR.LeaveRequest", b =>
                {
                    b.HasOne("UniCareERP.Domain.Entities.HR.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Employee");
                });

            modelBuilder.Entity("UniCareERP.Domain.Entities.Inventory.StockTransaction", b =>
                {
                    b.HasOne("UniCareERP.Domain.Entities.Inventory.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("InventoryItem");
                });

            // Added navigation collection to Invoice
            modelBuilder.Entity("UniCareERP.Domain.Entities.Finance.Invoice", b =>
                {
                    b.Navigation("InvoiceItems");
                });

#pragma warning restore 612, 618
        }
    }
}
